name: Test
on:
  push:
    branches:
      - staging
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
jobs:
  #for Push
  pushed_build:
    name: Build(pushed)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Zip artifact for upload
        run: cd out && zip ../out.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://liemdonduong.g.kuroco.app/direct/menu/github/"
          webhook_secret: "8b8397ab1860afe057e5cebfa055bca5"
          data: '{"single_zip":"0","domain":"liemdonduong.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
